import type { UseIdManagerParams, UseIdManagerReturnValue } from './use-id-manager.types';
import { useId as useQwikId, useConstant, useSignal, $ } from '@qwik.dev/core';

/**
 * An internal hook used to manage unique identifiers with support for prefixes and manual state control.
 *
 * This hook provides a flexible way to handle DOM identifiers, ensuring accessibility
 * and consistency across components. It encapsulates the complexity of generating unique IDs
 * while offering granular control through dedicated `QRL` functions.
 *
 * This hook is designed for internal library use to streamline dynamic ID orchestration,
 * manage compound components' sub-element tracking, and abstract state lifecycle updates.
 *
 * The generated identifier follows a specific structure:
 * `[prefix][baseId]`
 * - prefix: A string prepended to the ID (defaults to `entry-ui-qwik-`).
 * - baseId: Either a custom string provided via `generatedId` or a unique
 * sequence generated by the Qwik's `useId` hook.
 *
 * Example Outputs:
 * - Default: `"entry-ui-qwik-rs7mG5255s"` (where `"rs7mG5255s"` is the `autoId`)
 * - Custom prefix: `"my-app-header-rs7mG5255s"`
 * - Custom base: `"entry-ui-qwik-custom-id"`
 */
export const useIdManager = (params: UseIdManagerParams = {}): UseIdManagerReturnValue => {
  const { prefix = 'entry-ui-qwik-', generatedId, shouldInitialize = false } = params;

  // Retrieve an SSR-safe, automatically generated unique identifier string from Qwik's core primitives.
  // Guarantees stable unique scope identity across both server and client rendering passes.
  const autoId = useQwikId();

  // Memoize the core base identifier using `useConstant` to preserve reference stability across lifecycle updates.
  // Resolves to either the custom trimmed `generatedId` override or the auto-generated Qwik ID.
  const baseId = useConstant(() => (generatedId ? generatedId.trim() : autoId));

  // Initialize a reactive signal to hold the active string identifier state.
  // Conditionally pre-populates the formatted ID value on creation when `shouldInitialize` is enabled.
  const id = useSignal<string | undefined>(shouldInitialize ? `${prefix.trim()}${baseId}` : undefined);

  const set$ = $((value: string | undefined) => {
    // Check if a valid, non-empty string override was provided to assign.
    // Assigns the custom value directly or falls back to the default prefix and base ID combination.
    if (value && value.trim() !== '') {
      id.value = value;
    } else {
      id.value = `${prefix}${baseId}`;
    }
  });

  const delete$ = $(() => {
    // Reset the internal signal state to `undefined`.
    // Clears the active identifier reference for unmounting or deferred DOM targeting reset scenarios.
    id.value = undefined;
  });

  // Return the reactive readonly-wrapped signal reference and serialized mutation `QRL` handles.
  // Provides a complete identifier state management interface for consuming components.
  return { id, set$, delete$ };
};
