import type { UseIdManagerParams, UseIdManagerReturnValue } from './use-id-manager.types';
import { useId as useQwikId, useConstant, useSignal, $ } from '@qwik.dev/core';

/**
 * A hook that manages unique identifiers with support for prefixes and manual state control.
 *
 * This hook provides a flexible way to handle DOM identifiers, ensuring
 * accessibility and consistency across components. It encapsulates the
 * complexity of generating unique IDs while offering granular control
 * through dedicated `QRL` functions.
 *
 * The generated identifier follows a specific structure:
 * `[prefix][baseId]`
 * - prefix: A string prepended to the ID (defaults to `entry-ui-qwik-`).
 * - baseId: Either a custom string provided via `generatedId` or a unique
 * sequence generated by the Qwik's `useId` hook.
 *
 * Example Outputs:
 * - Default: `"entry-ui-qwik-rs7mG5255s"` (where `"rs7mG5255s"` is the `autoId`)
 * - Custom prefix: `"my-app-header-rs7mG5255s"`
 * - Custom base: `"entry-ui-qwik-custom-id"`
 */
export const useIdManager = (params: UseIdManagerParams = {}): UseIdManagerReturnValue => {
  const { prefix = 'entry-ui-qwik-', generatedId, shouldInitialize = false } = params;

  const autoId = useQwikId();
  const baseId = useConstant(() => (generatedId ? generatedId.trim() : autoId));
  const id = useSignal<string | undefined>(shouldInitialize ? `${prefix.trim()}${baseId}` : undefined);

  const set$ = $((value: string | undefined) => {
    if (value && value.trim() !== '') {
      id.value = value;
    } else {
      id.value = `${prefix}${baseId}`;
    }
  });

  const delete$ = $(() => {
    id.value = undefined;
  });

  return {
    id,
    set$,
    delete$,
  };
};
