import { ReadonlySignal, QRL } from '@qwik.dev/core';

/**
 * Configuration parameters for the `useIdManager` hook.
 */
export interface UseIdManagerParams {
  /**
   * An optional prefix to prepend to the generated or provided identifier.
   * This is useful for namespacing IDs to avoid collisions in the DOM,
   * especially when multiple instances of the same component are present.
   *
   * @default "entry-ui-qwik-"
   */
  prefix?: string;

  /**
   * An optional value to override the internal identifier.
   * When provided, this value will be used as the base for the identifier.
   * If omitted, the hook will fall back to a unique ID automatically
   * generated by the Qwik's `useId` hook.
   *
   * @default undefined
   */
  generatedId?: string;

  /**
   * Determines whether the identifier should be initialized immediately upon hook creation.
   * If set to `true`, the `id` readonly signal will be populated with the combined prefix and base ID on mount.
   * If `false`, the `id` readonly signal remains `undefined` until manually set via `set$`.
   *
   * @default false
   */
  shouldInitialize?: boolean;
}

/**
 * Represents the object returned by the `useIdManager` hook.
 */
export interface UseIdManagerReturnValue {
  /**
   * A readonly signal representing the current state of the identifier.
   * This signal is read-only, meaning its value can only be modified by calling
   * specific `QRL` functions like `set$` or `delete$`, ensuring consistent
   * and predictable state updates across the component tree.
   */
  id: ReadonlySignal<string | undefined>;

  /**
   * A `QRL` function that directly sets the identifier to a specific string value.
   * If a non-empty string is provided, it will be used as the new ID.
   * If the provided value is empty or undefined, the function will fall back
   * to the default format, combining the defined prefix and the base ID.
   */
  set$: QRL<(value: string | undefined) => void>;

  /**
   * A `QRL` function that clears the current identifier by setting its value to `undefined`.
   * This is particularly useful for resetting the state during component unmounting
   * or when the identifier is no longer required in the DOM.
   */
  delete$: QRL<() => void>;
}
