/**
 * Configuration parameters for the `useId` hook.
 */
export interface UseIdParams {
  /**
   * An optional prefix to prepend to the generated or provided identifier.
   * This helps in namespacing IDs to ensure uniqueness across the DOM,
   * particularly when multiple design system libraries or component instances coexist.
   *
   * @default "entry-ui-qwik-"
   */
  prefix?: string;

  /**
   * An optional value to override the internal identifier.
   * When provided, this value will be used as the base for the identifier.
   * If omitted, the hook will fall back to a unique ID automatically
   * generated by the Qwik's `useId` hook.
   *
   * @default undefined
   */
  generatedId?: string;
}
