import type { UseIdParams } from './use-id.types';
import { useId as useQwikId, useConstant } from '@qwik.dev/core';

/**
 * An internal hook used to generate stable, unique identifiers with support for custom prefixes and manual overrides.
 *
 * It combines Qwik's `useId` for SSR-safe uniqueness with `useConstant` for client-side stability,
 * ensuring that the identifier remains unchanged throughout the component's entire lifecycle.
 *
 * This hook is designed for internal library use to provide consistent IDs for accessibility (A11Y)
 * and DOM manipulation across various design system component implementations.
 *
 * The generated identifier follows a specific structure:
 * `[prefix][baseId]`
 * - prefix: A string prepended to the ID (defaults to `entry-ui-qwik-`).
 * - baseId: Either a custom string provided via `generatedId` or a unique
 * sequence generated by the Qwik's `useId` hook.
 *
 * Example Outputs:
 * - Default: `"entry-ui-qwik-rs7mG5255s"` (where `"rs7mG5255s"` is the `autoId`)
 * - Custom prefix: `"my-app-header-rs7mG5255s"`
 * - Custom base: `"entry-ui-qwik-custom-id"`
 */
export const useId = (params: UseIdParams = {}) => {
  const { prefix = 'entry-ui-qwik-', generatedId } = params;

  // Retrieve an SSR-safe, automatically generated unique identifier string from Qwik's core primitives.
  // This value guarantees unique scope identity across both server and client rendering passes.
  const autoId = useQwikId();

  // Compute and freeze the final formatted identifier string for the entirety of the component lifecycle.
  // Uses `useConstant` to ensure the constructed ID string remains completely invariant across re-renders.
  const id = useConstant(() => `${prefix.trim()}${generatedId ? generatedId.trim() : autoId}`);

  // Return the immutable final identifier string instance.
  // Serves as the primary stable identifier for DOM elements and accessibility associations.
  return id;
};
